export const initialProducts = [
 {id:'daily-bowl',name:'The everyday bowl',category:'Home & comfort',pets:['Dogs','Cats'],price:24,color:'#e6eade',ink:'#76866b',art:'bowl',badge:'Everyday favorite',detail:'A simple ceramic-style bowl with a reassuringly wide base. Made for the little ritual that starts every good day.',size:'One size · 600 ml'},
 {id:'good-dog',name:'Good dog bites',category:'Food & treats',pets:['Dogs'],price:14,color:'#f0e1cd',ink:'#a74d36',art:'food',badge:'A little reward',detail:'A sample treat collection for walks, training, and those very convincing puppy eyes. Illustrative packaging; ingredients will be supplied by the real retailer.',size:'Sample pack · 150 g'},
 {id:'twist-rope',name:'The happy tug',category:'Toys & play',pets:['Dogs'],price:18,color:'#e5e8e9',ink:'#cf7656',art:'toy',detail:'A chunky rope-inspired playmate for shared games and everyday enrichment. Choose toys to suit your pet’s size and supervise play.',size:'One size · 30 cm'},
 {id:'cloud-bed',name:'Cloud nine bed',category:'Home & comfort',pets:['Dogs','Cats'],price:68,color:'#eaded8',ink:'#aa7d68',art:'bed',badge:'Nap approved',detail:'Their own little corner of cozy. A soft, rounded bed concept in a warm oat shade that feels at home in your living room.',size:'Medium · 60 cm'},
 {id:'soft-shampoo',name:'Fresh start wash',category:'Grooming',pets:['Dogs'],price:22,color:'#e1e8dd',ink:'#597562',art:'bottle',detail:'A thoughtfully packaged grooming essential for the bath-day shelf. Sample product only; a real formula and suitability information will be added by the retailer.',size:'Sample bottle · 300 ml'},
 {id:'weekend-lead',name:'The wandering lead',category:'Walk essentials',pets:['Dogs'],price:32,color:'#ede4cf',ink:'#bd684a',art:'leash',badge:'Out & about',detail:'A warm terracotta lead concept with brass-tone hardware. A little everyday color for a lot of shared adventures.',size:'One size · 1.5 m'},
 {id:'cat-crunch',name:'Little purr bites',category:'Food & treats',pets:['Cats'],price:12,color:'#e7dfec',ink:'#7f6a8c',art:'food',detail:'A playful sample treat pack for your favorite feline. Final ingredients, feeding guidance, and dietary information belong to the actual store catalog.',size:'Sample pack · 100 g'},
 {id:'little-forager',name:'Little forager mix',category:'Food & treats',pets:['Birds','Small pets'],price:16,color:'#eee8ce',ink:'#7b8150',art:'food',detail:'A sample collection for little companions. A real retailer would specify the species, ingredients, and feeding guidance for each individual blend.',size:'Sample pack · 250 g'},
];
