import { useEffect, useState } from 'react';
import { ArrowLeft, ClipboardList, MessageCircle, PawPrint } from 'lucide-react';
import './admin-panel.css';
import './admin-inbox.css';

type InboxTab = 'orders' | 'support';
type InboxItem = { id: string; name: string; email: string; message?: string; items?: { name: string; quantity: number }[]; total?: number; delivery?: string; created_at: string; status: string };
async function request<T>(url: string, init: RequestInit = {}) { const response = await fetch(url, { ...init, credentials: 'same-origin', headers: { 'Content-Type': 'application/json', 'X-PawPass-Admin': '1', ...init.headers } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Request failed.'); return data as T; }
export default function AdminInbox() {
 const [tab, setTab] = useState<InboxTab>('orders'); const [items, setItems] = useState<InboxItem[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
 useEffect(() => { setLoading(true); void request<InboxItem[]>(`/api/admin/${tab}`).then(setItems).catch(e => { if (e instanceof Error && e.message.includes('sign in')) window.location.href = '/admin'; else setError(e instanceof Error ? e.message : 'Unable to load inbox.'); }).finally(() => setLoading(false)); }, [tab]);
 async function update(id: string, status: string) { try { await request(`/api/admin/${tab}/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); setItems(current => current.map(item => item.id === id ? { ...item, status } : item)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update status.'); } }
 return <main className="admin-shell"><header className="admin-topbar"><a className="admin-brand" href="/admin"><PawPrint size={25} fill="currentColor" /><span>pawpass<sup>®</sup></span></a><span className="admin-topbar-label">CUSTOMER INBOX</span><a className="admin-shop-link" href="/admin"><ArrowLeft size={16} /> Back to catalog</a></header><div className="admin-content"><header className="admin-header"><div><span className="admin-kicker">ORDERS AND SUPPORT</span><h1>Stay close to <em>every customer.</em></h1><p>Orders and customer questions arrive here for your team to review.</p></div></header><nav className="admin-tabs" aria-label="Customer inbox sections"><button aria-pressed={tab === 'orders'} onClick={() => setTab('orders')}><ClipboardList size={15}/> Orders</button><button aria-pressed={tab === 'support'} onClick={() => setTab('support')}><MessageCircle size={15}/> Support requests</button></nav>{error&&<p className="admin-error" role="alert">{error}</p>}{loading?<div className="admin-loading"><PawPrint size={30}/><p>Opening the inbox…</p></div>:!items.length&&!error?<div className="admin-empty"><PawPrint size={30}/><p>No {tab === 'orders' ? 'orders' : 'support requests'} yet.</p></div>:<section className="admin-inbox-list">{items.map(item => <article className="admin-inbox-item" key={item.id}><div><span className="admin-kicker">{item.id} · {new Date(item.created_at).toLocaleString()}</span><h3>{item.name} <small>{item.email}</small></h3>{tab === 'orders' ? <><p>{item.items?.map(line => `${line.name} × ${line.quantity}`).join(', ')}</p><strong>${Number(item.total).toFixed(2)} · {item.delivery === 'pickup' ? 'Pickup' : 'Delivery'}</strong></> : <p>{item.message}</p>}</div><select value={item.status} onChange={event => void update(item.id, event.target.value)} aria-label={`Update ${item.id} status`}>{(tab === 'orders' ? ['new', 'confirmed', 'complete', 'cancelled'] : ['new', 'in_progress', 'resolved']).map(status => <option key={status} value={status}>{status.replace('_', ' ')}</option>)}</select></article>)}</section>}</div></main>;
}
