import { useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, CalendarDays, Check, Dog, HeartHandshake, Search, Star } from 'lucide-react';
import { z } from 'zod';

const petSchema = z.object({ name: z.string().min(1).max(50), kind: z.string(), breed: z.string().max(80), age: z.string().max(30) });
const orderSchema = z.object({ id: z.string(), pet: z.string(), provider: z.string(), service: z.string(), date: z.string(), time: z.string(), recurring: z.boolean(), total: z.number(), cancelled: z.boolean() });
type Pet = z.infer<typeof petSchema>;
type Order = z.infer<typeof orderSchema>;
const carers = [
 { name: 'Maya Chen', initials: 'MC', services: ['Walks', 'Home visits'], kinds: ['Dog', 'Cat'], rating: 5, price: 24, detail: 'Patient walks and familiar routines for your four-legged friend.', color: '#ead9d1' },
 { name: 'Luis Rivera', initials: 'LR', services: ['Grooming'], kinds: ['Dog', 'Cat'], rating: 4.9, price: 38, detail: 'Gentle grooming, a calm studio, and plenty of time to settle in.', color: '#dcebe7' },
 { name: 'Nora Patel', initials: 'NP', services: ['Home visits'], kinds: ['Bird', 'Rabbit', 'Cat', 'Dog'], rating: 4.8, price: 20, detail: 'Thoughtful check-ins for little companions, wings and whiskers included.', color: '#f5e2b7' },
];
function read<T>(key: string, schema: z.ZodType<T>, fallback: T): T {
 try { const result = schema.safeParse(JSON.parse(localStorage.getItem(key) || 'null')); return result.success ? result.data : fallback; } catch { return fallback; }
}
function localDate(offset = 1) { const d = new Date(); d.setDate(d.getDate() + offset); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
function prettyDate(date: string) { return new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { month: 'short', day: 'numeric', weekday: 'short' }); }
export default function CarePreview() {
 const [page, setPage] = useState('home');
 const [pet, setPet] = useState<Pet>(() => read('pawpass.pet.v1', petSchema, { name: 'Beans', kind: 'Dog', breed: 'Golden retriever', age: '4 years' }));
 const [orders, setOrders] = useState<Order[]>(() => read('pawpass.orders.v1', z.array(orderSchema), []));
 const [service, setService] = useState('All services');
 const [search, setSearch] = useState('');
 const [topRated, setTopRated] = useState(false);
 const [provider, setProvider] = useState(carers[0]);
 const [date, setDate] = useState(localDate);
 const [time, setTime] = useState('09:30');
 const [recurring, setRecurring] = useState(false);
 const [error, setError] = useState('');
 const [lastOrder, setLastOrder] = useState<Order>();
 const [activeOnly, setActiveOnly] = useState(true);
 const navigate = (next: string) => { setError(''); setPage(next); };
 const save = (key: string, value: unknown) => { try { localStorage.setItem(key, JSON.stringify(value)); return true; } catch { setError('Your browser could not save this. Please allow browser storage and try again.'); return false; } };
 const savePet = (event: FormEvent) => { event.preventDefault(); const next = { ...pet, name: pet.name.trim() }; if (!next.name) { setError('Please enter your pet’s name.'); return; } if (save('pawpass.pet.v1', next)) { setPet(next); navigate('browse'); } };
 const confirm = () => {
  if (date < localDate() || !pet.name.trim()) { setError('Choose a future date and enter your pet’s name.'); return; }
  const order: Order = { id: crypto.randomUUID(), pet: pet.name, provider: provider.name, service, date, time, recurring, total: provider.price * 1.1, cancelled: false };
  const next = [order, ...orders]; if (save('pawpass.orders.v1', next)) { setOrders(next); setLastOrder(order); navigate('confirmed'); }
 };
 const back: Record<string,string> = { pet:'home', browse:'home', provider:'browse', schedule:'provider', review:'schedule', orders:'home', confirmed:'home' };
 const filtered = carers.filter(c => (service === 'All services' || c.services.includes(service)) && c.kinds.includes(pet.kind) && (!topRated || c.rating >= 4.9) && `${c.name} ${c.services.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="preview-shell care-app" aria-label="Interactive pet care demo">
  <div className="care-banner"><span>PAWPASS PLAYGROUND</span><span>Demo · no charges</span></div>
  <div className="care-heading"><button aria-label="Back to previous screen" disabled={page === 'home'} onClick={() => navigate(back[page] || 'home')}><ArrowLeft size={18}/></button><strong>{({home:'Your little care corner',pet:'Meet your companion',browse:'Find their person',provider:'A friendly face',schedule:'Make a little time',review:'Review your demo',confirmed:'All set!',orders:'Your care orders'} as Record<string,string>)[page]}</strong><HeartHandshake size={20}/></div>
  <div className="care-content" key={page}>
  {error && <p role="alert" className="care-error">{error}</p>}
  {page === 'home' && <><div className="care-welcome"><span className="eyebrow">A happier day starts here</span><h3 className="serif">Hello, {pet.name}’s human.</h3><p>A walk, a fresh trim, a little company. Let’s find the right care.</p><Dog size={40}/></div><button className="care-row" onClick={() => navigate('pet')}><span><strong>{pet.name}</strong><small>{pet.kind} · Edit pet profile</small></span><ArrowRight size={18}/></button><h4>What do they need?</h4><div className="care-services">{['Walks','Grooming','Home visits'].map((s,i) => <button key={s} onClick={() => { setService(s); navigate('browse'); }}><span>{['🐾','✂️','🏡'][i]}</span>{s}</button>)}</div><button className="care-row" onClick={() => navigate('orders')}><span><strong>Your saved care</strong><small>{orders.filter(o => !o.cancelled).length} active demo bookings</small></span><CalendarDays size={20}/></button><button className="button-primary care-primary" onClick={() => { setService('All services'); navigate('browse'); }}>Explore providers <ArrowRight size={16}/></button></>}
  {page === 'pet' && <form onSubmit={savePet}><p>Make this little space their own.</p><label>Pet’s name<input required maxLength={50} value={pet.name} onChange={e => setPet({...pet,name:e.target.value})}/></label><label>Pet type<select value={pet.kind} onChange={e => setPet({...pet,kind:e.target.value,breed:''})}>{['Dog','Cat','Bird','Rabbit'].map(k => <option key={k}>{k}</option>)}</select></label><label>Breed or type<input maxLength={80} value={pet.breed} onChange={e => setPet({...pet,breed:e.target.value})}/></label><label>Age<input maxLength={30} value={pet.age} onChange={e => setPet({...pet,age:e.target.value})}/></label><button className="button-primary care-primary">Save & find care <ArrowRight size={16}/></button></form>}
  {page === 'browse' && <><label className="care-search"><Search size={16}/><input aria-label="Search providers" placeholder="Search by name or service" value={search} onChange={e => setSearch(e.target.value)}/></label><label>Service<select value={service} onChange={e => setService(e.target.value)}>{['All services','Walks','Grooming','Home visits'].map(s => <option key={s}>{s}</option>)}</select></label><label className="care-check"><input type="checkbox" checked={topRated} onChange={e => setTopRated(e.target.checked)}/> Top rated (4.9+)</label><p className="care-muted">{filtered.length} sample providers for your {pet.kind.toLowerCase()}</p>{filtered.map(c => <button className="care-row" key={c.name} onClick={() => { setProvider(c); if (!c.services.includes(service)) setService(c.services[0]); navigate('provider'); }}><span className="care-avatar" style={{background:c.color}}>{c.initials}</span><span><strong>{c.name}</strong><small>{c.services.join(' & ')}</small><small>★ {c.rating.toFixed(1)} · From ${c.price}/visit</small></span><ArrowRight size={16}/></button>)}{!filtered.length && <div className="care-empty"><p>No matches just yet. Try another service or update your filters.</p><button onClick={() => {setSearch('');setTopRated(false);setService('All services');}}>Clear filters</button></div>}</>}
  {page === 'provider' && <><div className="care-provider"><span className="care-avatar" style={{background:provider.color}}>{provider.initials}</span><h3 className="serif">{provider.name}</h3><p><Star size={14}/> {provider.rating.toFixed(1)} · Sample profile</p></div><p>{provider.detail}</p><div className="care-summary"><strong>{service}</strong><p>From ${provider.price} per visit + 10% care fee</p><small>Available for {provider.kinds.join(', ').toLowerCase()}.</small></div><button className="button-primary care-primary" onClick={() => navigate('schedule')}>Choose {provider.name.split(' ')[0]} <ArrowRight size={16}/></button></>}
  {page === 'schedule' && <form onSubmit={e => {e.preventDefault();navigate('review');}}><p>{service} with <strong>{provider.name}</strong> for {pet.name}.</p><label>Visit date<input type="date" required min={localDate()} value={date} onChange={e => setDate(e.target.value)}/></label><label>Visit time<select value={time} onChange={e => setTime(e.target.value)}>{['09:30','11:00','14:30','16:00','17:30'].map(t => <option key={t}>{t}</option>)}</select></label><label className="care-check"><input type="checkbox" checked={recurring} onChange={e => setRecurring(e.target.checked)}/> Repeat weekly at this time</label><p className="care-muted">Times are illustrative. This playground does not check real provider availability.</p><button className="button-primary care-primary">Review booking <ArrowRight size={16}/></button></form>}
  {page === 'review' && <><div className="care-summary"><strong>{service} with {provider.name}</strong><p>{prettyDate(date)} · {time}</p><p>For {pet.name} · {recurring ? 'Weekly' : 'One visit'}</p></div><div className="care-row"><span>Visit</span><strong>${provider.price.toFixed(2)}</strong></div><div className="care-row"><span>Care fee</span><strong>${(provider.price*.1).toFixed(2)}</strong></div><div className="care-row"><strong>Demo total per visit</strong><strong>${(provider.price*1.1).toFixed(2)}</strong></div><p className="care-muted">No payment details needed. This saves a demo booking on this browser only; no provider is contacted.</p><button className="button-primary care-primary" onClick={confirm}>Save demo booking <Check size={16}/></button></>}
  {page === 'confirmed' && lastOrder && <div className="care-confirmed"><span className="care-success"><Check size={34}/></span><h3 className="serif">A little peace of mind.</h3><p>{lastOrder.pet}’s demo {lastOrder.service.toLowerCase()} with {lastOrder.provider} is saved for {prettyDate(lastOrder.date)} at {lastOrder.time}.</p><p className="care-muted">You can revisit or cancel it in your saved care.</p><button className="button-primary care-primary" onClick={() => navigate('orders')}>View care orders <ArrowRight size={16}/></button></div>}
  {page === 'orders' && <><label className="care-check"><input type="checkbox" checked={activeOnly} onChange={e => setActiveOnly(e.target.checked)}/> Show active only</label>{orders.filter(o => !activeOnly || !o.cancelled).map(o => <div className="care-summary" key={o.id}><small>{o.cancelled ? 'Cancelled' : 'Saved demo'} · {o.recurring ? 'Weekly' : 'One visit'}</small><h4>{o.service} with {o.provider}</h4><p>{o.pet} · {prettyDate(o.date)} · {o.time}</p><p>${o.total.toFixed(2)} / visit</p>{!o.cancelled && <button className="care-cancel" onClick={() => { const next = orders.map(item => item.id === o.id ? {...item,cancelled:true} : item); if(save('pawpass.orders.v1',next)) setOrders(next); }}>Cancel demo booking</button>}</div>)}{!orders.some(o => !activeOnly || !o.cancelled) && <div className="care-empty"><CalendarDays size={30}/><h4>A little room for care.</h4><p>No {activeOnly ? 'active ' : ''}bookings yet. Find a friendly face to get started.</p></div>}<button className="button-primary care-primary" onClick={() => navigate('browse')}>Find care <ArrowRight size={16}/></button></>}
  </div><div className="care-bottom">Made for practice. Saved on this browser.</div>
 </div>;
}
